enum WINDOW_NAME {
  LOGIN_WINDOW = 'LOGIN_WINDOW',
  REISTER_WINDOW = 'REGISTE_WINDOW',
  MAIN_WINDOW = 'MAIN_WINDOW',
  SCREEN_SHARE_WINDOW = 'SCREEN_SHARE_WINDOW',
  VIDEO_WINDOW = 'VIDEO_WINDOW',
  EDIT_PROFILE_WINDOW = 'EDIT_PROFILE_WINDOW',
  ADD_FRIEND_WINDOW = 'ADD_FRIEND_WINDOW',
}

export { WINDOW_NAME }
