name: Build Electron App For Win/Mac/Ubuntu
on:
  push:
    branches:
      - main
      - 'v*.*.*'
jobs:
  build:
    name: build electron app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-20.04]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build electron app
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
